services:
  api:
    image: api
    container_name: api_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      APP_PORT: 8080
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: iot_devices_tracker
      DB_HOST: db
      DB_PORT: 5432

  db:
    container_name: db
    build:
      context: ./
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: iot_devices_tracker

    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  pg_data:
